from __future__ import annotations

OBJECT_TRACK_COLUMNS = [
    "video_uid",
    "video_path",
    "frame",
    "time_sec",
    "fps",
    "track_id",
    "cls_id",
    "cls_name",
    "det_confidence",
    "x1",
    "y1",
    "x2",
    "y2",
    "box_w",
    "box_h",
    "area_px",
    "area_rel",
    "cx",
    "cy",
    "cx_norm",
    "cy_norm",
    "dist_center_norm",
    "mean_r",
    "mean_g",
    "mean_b",
    "center_r",
    "center_g",
    "center_b",
    "rgb_spread_rms",
    "rgb_spread_mean",
    "mean_h",
    "mean_s",
    "mean_v",
    "mean_L",
    "mean_a",
    "mean_b_lab",
    "mean_a_c",
    "mean_b_c",
    "std_L",
    "std_a",
    "std_b_lab",
    "contrast_gray_std",
    "orientation_deg",
    "vx_px_s",
    "vy_px_s",
    "speed_px_s",
    "dir_deg",
    "accel_px_s2",
    "flow_mag_mean_px_per_frame",
    "flow_mag_mean_px_per_s",
    "flow_ang_mean_deg",
    "flow_divergence",
    "camera_motion_px_per_frame",
    "object_relative_motion_px_per_frame",
    "mask_area_px",
    "mask_area_rel",
    "mask_eccentricity",
    "track_age_frames",
    "entry_event",
    "exit_event",
    "occluded",
    "saliency_score",
    "temporal_rgb_drift",
    "traj_pred_err_px",
    "feature_pred_err",
    "embedding_clip_norm",
    "embedding_dinov2_norm",
    "typicality_score",
    "novelty_score",
]

FRAME_STAT_COLUMNS = [
    "video_uid",
    "video_path",
    "frame",
    "time_sec",
    "fps",
    "n_objects",
    "n_tracks_confirmed",
    "mean_area_rel",
    "mean_confidence",
    "mean_speed_px_s",
    "mean_saliency",
    "scene_motion_mean",
    "scene_motion_std",
    "temporal_autocorr_gray",
    "feature_predictability_mean",
]

QC_COLUMNS = [
    "video_uid",
    "status",
    "frames_read",
    "frames_written",
    "objects_written",
    "nan_rate_object_tracks",
    "track_fragmentation_proxy",
    "error",
]


def missing_columns(columns: list[str] | set[str], required: list[str]) -> list[str]:
    present = set(columns)
    return [c for c in required if c not in present]

